Ap 35 properties implementieren
DarkModz-Official/Azubi-Projekt pull request #10
Opened 2022-11-11 19:51 UTC by DarkModz-Official

# added
Properties implemented
#AP-35 #done

2022-11-13 00:20 UTC, keksgauner commented on src/main/java/org/devcloud/ap/Azubiprojekt.java
> +        Config config = new Config();
Besser in damit eine static variable zu erstellen um von außerhalb mit einer Methode zuzugreifen zu können.

2022-11-13 01:42 UTC, keksgauner requested changes
### Als Wichtig eingestuft
Es fehlt eine Schnittstelle um daten zu Speichern. 
Es fehlt eine Konfiguration Speicherung nach dem Setup. 
Es fehlt ein Zentraler Konfiguration Schnittstelle, damit es nur einmal bei dem Start geladen werden muss. Keine Möglichkeit das Setup aufzurufen. 

### Als Geringfügig eingestuft
Die Variablen public zu machen ist schlecht für die Verkapselung und kann von überall aus verändert werden somit keine Validierung möglich. Somit bitte abändern. Mehr Infos java:S1104 (SonarLint)

2022-11-13 01:42 UTC, keksgauner commented on src/main/java/org/devcloud/ap/utils/HTTPServer.java
> +    private static Config config = new Config();
Über die Main auf eine Methode zugreifen. (Diese existiert nicht)

2022-11-13 01:42 UTC, keksgauner commented on src/main/java/org/devcloud/ap/utils/SentryLogger.java
> +    private static Config config = new Config();
Doppeltes erstellen des Konfiguration Object. Es ist im Projekt 3 mal vorhanden. Es reicht einmal in der Main eine static variable zu erstellen.

2022-11-13 01:42 UTC, keksgauner commented on src/main/java/org/devcloud/ap/Azubiprojekt.java
> +        Config config = new Config();
Besser in damit eine static variable zu erstellen um von außerhalb mit einer Methode zuzugreifen zu können.

2022-11-13 01:42 UTC, keksgauner commented on src/main/java/org/devcloud/ap/utils/SentryLogger.java
> +        config.initConfig();
Einmal initialisieren in der Main und eine Methode nutzen. Somit wird bei dem Start nicht  doppelt aus der Konfiguration gelesen.

2022-11-13 01:42 UTC, keksgauner commented on src/main/java/org/devcloud/ap/utils/Config.java
> +        logger.info("Please enter the Database Host:");
Diskussion. Sollte die Anwendung Deutsch oder Englisch sein?
Bitte für mehr Informationen. Denn das GUI ist größtenteils Deutsch.

2022-11-13 01:42 UTC, keksgauner commented on src/main/java/org/devcloud/ap/utils/Config.java
> +            props.load(Azubiprojekt.class.getClassLoader().getResourceAsStream("config.properties"));
Es wäre sinnvoll diese Config aus den Resource Ordner reinzukopieren und diese dann zu laden.
Damit die Konfiguration nicht in der Jar selbst eingestellt wird

2022-11-13 01:42 UTC, keksgauner commented on src/main/resources/config.properties
> +# Database Configuration
Setup wird nur bei leerer Config ausgeführt wie in getProperties zu sehen ist

2022-11-13 01:42 UTC, keksgauner commented on src/main/java/org/devcloud/ap/utils/Config.java
> +        if (props.isEmpty()) {
Fragt ab ob keine Inhalte der Property vorhanden ist. Das ist schlecht da es sein kann, dass einzelne punkte fehlen. Somit wird kein Setup ausgeführt obwohl etwas nötig wäre.

Unteranderem wenn nichts in der Config steht oder die Config nicht existiert wird es hier Fehler geben und zusätzlich wird kein Setup ausgeführt.

2022-11-13 01:42 UTC, keksgauner commented on src/main/java/org/devcloud/ap/utils/Config.java
> +        Scanner scanner = new Scanner(System.in);
Es wird hier zwar alles reingelesen aber nicht in die Config gespeichert. Es wird nur lokal mit put abgeändert. Somit ist createConfig nur für eine Session verändert. Hier fehlt das Speichern der veränderten Config in die eigentliche Config

2022-11-13 01:42 UTC, keksgauner commented on src/main/java/org/devcloud/ap/utils/Config.java
> +    }
Hier fehlt das Speichern der Config
Mit: `props.store(new FileOutputStream("config.properties"), null);` Speicherst du die Config dort wo die Jar lebt.
Setzt aber voraus, dass die Config außerhalb der Jar geladen wird

2022-11-13 01:42 UTC, keksgauner commented on src/main/java/org/devcloud/ap/utils/Config.java
> +        var dbHost = scanner.nextLine();
Anstatt var ist es möglich ein String zu nehmen.
Bei var muss vor dem Kompilieren klar sein welcher Datentype es ist.
Deshalb ist null nicht erlaubt. Es wäre nach meiner Meinung besser den Datentype festzulegen, damit es nicht aus irgendwelchen gründen auch immer wechselt. Weil so etwas eher nicht vor kommt, würde ich sagen, es macht hier keine Probleme und muss nicht verändert werden.

2022-11-13 01:42 UTC, keksgauner commented on src/main/java/org/devcloud/ap/utils/Config.java
> +    public String debugmode;
debugmode ist ein String?

2022-12-28 21:59 UTC, DarkModz-Official commented
![Quality gate](https://app.embold.io/organization/gh/DarkModz-Official/repositories/f8c8a5bc36e1dde48a86617291ef4643/pull-request/10/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* ![Vulnerability](https://app.embold.io/organization/gh/DarkModz-Official/repositories/f8c8a5bc36e1dde48a86617291ef4643/pull-request/10/assets/images/svg/vulnerability.svg) 2 Vulnerabilities 
 * ![Code issue](https://app.embold.io/organization/gh/DarkModz-Official/repositories/f8c8a5bc36e1dde48a86617291ef4643/pull-request/10/assets/images/svg/code-issue.svg) 3 Code issues 

 [Details](https://app.embold.io/organization/gh/DarkModz-Official/repositories/f8c8a5bc36e1dde48a86617291ef4643/pull-request/10)

2026-03-16 08:33 UTC, keksgauner commented
Es gibt keinen Grund, dass dieser Merch noch erfolgen sollte somit schließe ich das.

2026-03-16 08:33 UTC, closed without merging